export const categoryList=[
   {
     name:'Electronic',
     url:'/electronic'
    },
   {
     name:'Fashion',
     url:'/electronic'
    },
   {
     name:'Beauty',
     url:'/electronic'
    },
   {
     name:'Medecine',
     url:'/electronic'
    },
   {
     name:'Gadget',
     url:'/electronic'
    },
   {
     name:'Decocratioon',
     url:'/electronic'
    },
   {
     name:'Grocery',
     url:'/electronic'
    },
   {
     name:'Sports',
     url:'/electronic'
    },
   {
     name:'Lifestyle',
     url:'/electronic'
    },
]